// ─────────────────────────────────────────────
// Static Data for Japan Physics PhD Finder Agent
// For Nepali MSc Physics Students from Tribhuvan University
// ─────────────────────────────────────────────

export interface Institution {
  id: string
  name: string
  city: string
  country: string  // Japanese prefecture
  type: 'University' | 'Research Institute' | 'National Institute'
  department: string
  researchGroup: string | null
  url: string
  fields: string
  phdType: string
  deadline: string
  admission: 'Rolling' | 'Semester-based'
  deadlines: {
    april_intake: string
    october_intake: string
    rolling: boolean
  }
  internationalTuitionJpy: number
  funding: {
    doctoralScholarshipAvailable: boolean
    doctoralStipendJpy: number
    mextEligible: boolean
    jspsEligible: boolean
    imperialUniversity: boolean
    jspSKakenhi: boolean
  }
  ieltsMinimum: number
  contractType: string
  monthlyJpy: number | null
  languageInstruction: string
  englishLabLife: boolean
  notableProfessors: string
  requiredDocuments: string
  notesForNepali: string
  watchlisted: boolean
  lastUpdated: string
  go8: boolean // Imperial University flag for API compat
}

export interface ScholarshipInfo {
  id: string
  title: string
  category: string
  content: string
}

// ─────────────────────────────────────────────
// JAPANESE UNIVERSITIES & RESEARCH INSTITUTES
// ─────────────────────────────────────────────
export const institutions: Institution[] = [
  // ========================
  // IMPERIAL UNIVERSITIES (旧帝大)
  // ========================
  {
    id: 'utokyo',
    name: 'The University of Tokyo',
    city: 'Tokyo',
    country: 'Tokyo',
    type: 'University',
    department: 'Graduate School of Science, Department of Physics',
    researchGroup: 'Quantum Physics, Astrophysics, Condensed Matter',
    url: 'https://www.phys.s.u-tokyo.ac.jp/',
    fields: 'Quantum Physics|Astrophysics|Condensed Matter|Particle Physics|Nuclear Physics|Biophysics',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Nov prior year', october_intake: 'May same year', rolling: true },
    internationalTuitionJpy: 535800,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 143000,
      mextEligible: true,
      jspsEligible: true,
      imperialUniversity: true,
      jspSKakenhi: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'MEXT Scholarship or JSPS Fellowship',
    monthlyJpy: 143000,
    languageInstruction: 'English (many groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Takaaki Kajita (Nobel Laureate, Neutrino Physics), Prof. Hidetoshi Katori (Quantum Metrology)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL, motivation letter',
    notesForNepali: 'UTokyo is Japan\'s top-ranked university. MEXT covers full tuition + ¥143,000/month + airfare from Nepal. Many research groups operate entirely in English.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: true,
  },
  {
    id: 'kyoto-u',
    name: 'Kyoto University',
    city: 'Kyoto',
    country: 'Kyoto',
    type: 'University',
    department: 'Graduate School of Science, Department of Physics',
    researchGroup: 'Theoretical Physics, Nuclear Physics, Particle Physics',
    url: 'https://www.phys.kyoto-u.ac.jp/',
    fields: 'Theoretical Physics|Nuclear Physics|Particle Physics|Condensed Matter|Astrophysics|Quantum Mechanics',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Nov prior year', october_intake: 'May same year', rolling: true },
    internationalTuitionJpy: 535800,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 143000,
      mextEligible: true,
      jspsEligible: true,
      imperialUniversity: true,
      jspSKakenhi: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'MEXT Scholarship or JSPS Fellowship',
    monthlyJpy: 143000,
    languageInstruction: 'English (many groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Tetsuo Hatsuda (Theoretical Nuclear Physics), Prof. Hirosi Ooguri (String Theory)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL, motivation letter',
    notesForNepali: 'KyotoU is Japan\'s second oldest university with strong physics tradition. MEXT fully funded. Known for Theoretical Physics and Yukawa Institute.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: true,
  },
  {
    id: 'osaka-u',
    name: 'Osaka University',
    city: 'Osaka',
    country: 'Osaka',
    type: 'University',
    department: 'Graduate School of Science, Department of Physics',
    researchGroup: 'Quantum Information, Photonics, Biophysics',
    url: 'https://www.sci.osaka-u.ac.jp/',
    fields: 'Quantum Information|Photonics|Biophysics|Condensed Matter|Particle Physics|Nuclear Physics',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Nov prior year', october_intake: 'May same year', rolling: true },
    internationalTuitionJpy: 535800,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 143000,
      mextEligible: true,
      jspsEligible: true,
      imperialUniversity: true,
      jspSKakenhi: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'MEXT Scholarship or JSPS Fellowship',
    monthlyJpy: 143000,
    languageInstruction: 'English (many groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Makoto Kobayashi (Nobel Laureate, Particle Physics), Prof. Hidetoshi Nakazato (Quantum Information)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL, motivation letter',
    notesForNepali: 'Osaka University is strong in Quantum Information and Photonics. MEXT covers everything. KAVLI IPMU connections available.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: true,
  },
  {
    id: 'tohoku-u',
    name: 'Tohoku University',
    city: 'Sendai',
    country: 'Miyagi',
    type: 'University',
    department: 'Graduate School of Science, Department of Physics',
    researchGroup: 'Materials Science, Magnetism, Spintronics',
    url: 'https://www.sci.tohoku.ac.jp/',
    fields: 'Materials Science|Magnetism|Spintronics|Condensed Matter|Nuclear Physics|Particle Physics',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Nov prior year', october_intake: 'May same year', rolling: true },
    internationalTuitionJpy: 535800,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 143000,
      mextEligible: true,
      jspsEligible: true,
      imperialUniversity: true,
      jspSKakenhi: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'MEXT Scholarship or JSPS Fellowship',
    monthlyJpy: 143000,
    languageInstruction: 'English (many groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Eiji Saitoh (Spintronics), Prof. Hidenori Takagi (Condensed Matter)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL, motivation letter',
    notesForNepali: 'Tohoku University is the top university for Materials Science and Spintronics. MEXT fully funded. Lower cost of living in Sendai.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: true,
  },
  {
    id: 'nagoya-u',
    name: 'Nagoya University',
    city: 'Nagoya',
    country: 'Aichi',
    type: 'University',
    department: 'Graduate School of Science, Department of Physics',
    researchGroup: 'Particle Physics, Astrophysics, Quantum Mechanics',
    url: 'https://www.phys.nagoya-u.ac.jp/',
    fields: 'Particle Physics|Astrophysics|Quantum Mechanics|Condensed Matter|Theoretical Physics|Nuclear Physics',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Nov prior year', october_intake: 'May same year', rolling: true },
    internationalTuitionJpy: 535800,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 143000,
      mextEligible: true,
      jspsEligible: true,
      imperialUniversity: true,
      jspSKakenhi: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'MEXT Scholarship or JSPS Fellowship',
    monthlyJpy: 143000,
    languageInstruction: 'English (many groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Makoto Kobayashi (Nobel Laureate), Prof. Toshihide Maskawa (Nobel Laureate)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL, motivation letter',
    notesForNepali: 'Nagoya University has a rich Nobel Prize tradition in Particle Physics. MEXT fully funded. Home of the Kobayashi-Maskawa theory.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: true,
  },
  {
    id: 'hokkaido-u',
    name: 'Hokkaido University',
    city: 'Sapporo',
    country: 'Hokkaido',
    type: 'University',
    department: 'Graduate School of Science, Department of Physics',
    researchGroup: 'Condensed Matter, Low-Temperature Physics, Environmental Physics',
    url: 'https://www.sci.hokudai.ac.jp/',
    fields: 'Condensed Matter|Low-Temperature Physics|Environmental Physics|Quantum Physics|Materials Science|Biophysics',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Nov prior year', october_intake: 'May same year', rolling: true },
    internationalTuitionJpy: 535800,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 143000,
      mextEligible: true,
      jspsEligible: true,
      imperialUniversity: true,
      jspSKakenhi: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'MEXT Scholarship or JSPS Fellowship',
    monthlyJpy: 143000,
    languageInstruction: 'English (many groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Hiroyuki Nojiri (High Magnetic Fields), Prof. Terufumi Yamaguchi (Particle Physics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL, motivation letter',
    notesForNepali: 'Hokkaido University is excellent for Low-Temperature Physics and Condensed Matter. MEXT fully funded. Sapporo has beautiful nature and lower living costs.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: true,
  },
  {
    id: 'kyushu-u',
    name: 'Kyushu University',
    city: 'Fukuoka',
    country: 'Fukuoka',
    type: 'University',
    department: 'Graduate School of Science, Department of Physics',
    researchGroup: 'Quantum Optics, Applied Physics, Nuclear Physics',
    url: 'https://www.sci.kyushu-u.ac.jp/',
    fields: 'Quantum Optics|Applied Physics|Nuclear Physics|Particle Physics|Condensed Matter|Photonics',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Nov prior year', october_intake: 'May same year', rolling: true },
    internationalTuitionJpy: 535800,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 143000,
      mextEligible: true,
      jspsEligible: true,
      imperialUniversity: true,
      jspSKakenhi: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'MEXT Scholarship or JSPS Fellowship',
    monthlyJpy: 143000,
    languageInstruction: 'English (many groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Shozo Yanagiya (Quantum Optics), Prof. Nobuaki Imai (Nuclear Physics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL, motivation letter',
    notesForNepali: 'Kyushu University is one of the Imperial Universities with strong Quantum Optics and Applied Physics. MEXT fully funded. Fukuoka has great food and lower costs.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: true,
  },

  // ========================
  // OTHER TOP UNIVERSITIES
  // ========================
  {
    id: 'tokyotech',
    name: 'Tokyo Institute of Technology (Tokyo Tech)',
    city: 'Tokyo',
    country: 'Tokyo',
    type: 'University',
    department: 'School of Science, Department of Physics',
    researchGroup: 'Condensed Matter, Quantum Computing, Materials Science',
    url: 'https://www.phys.titech.ac.jp/',
    fields: 'Condensed Matter|Quantum Computing|Materials Science|Theoretical Physics|Photonics|Nuclear Physics',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Nov prior year', october_intake: 'May same year', rolling: true },
    internationalTuitionJpy: 535800,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 143000,
      mextEligible: true,
      jspsEligible: true,
      imperialUniversity: false,
      jspSKakenhi: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'MEXT Scholarship or JSPS Fellowship',
    monthlyJpy: 143000,
    languageInstruction: 'English (many groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Hidetoshi Katori (Quantum Metrology), Prof. Naoto Nagaosa (Theoretical Condensed Matter)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL, motivation letter',
    notesForNepali: 'Tokyo Tech is Japan\'s top technical university, comparable to UTokyo in science. MEXT fully funded. Strong in Quantum Computing and Materials Science.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'tsukuba-u',
    name: 'University of Tsukuba',
    city: 'Tsukuba',
    country: 'Ibaraki',
    type: 'University',
    department: 'Graduate School of Pure and Applied Sciences',
    researchGroup: 'Particle Physics, Materials Science',
    url: 'https://www.tsukuba.ac.jp/',
    fields: 'Particle Physics|Materials Science|Condensed Matter|Quantum Physics|Astrophysics|Nuclear Physics',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Nov prior year', october_intake: 'May same year', rolling: true },
    internationalTuitionJpy: 535800,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 143000,
      mextEligible: true,
      jspsEligible: true,
      imperialUniversity: false,
      jspSKakenhi: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'MEXT Scholarship or JSPS Fellowship',
    monthlyJpy: 143000,
    languageInstruction: 'English (many groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Koichiro Nishikawa (Particle Physics, T2K experiment)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL, motivation letter',
    notesForNepali: 'Tsukuba is Japan\'s Science City — home to KEK and many national institutes. MEXT fully funded. Great environment for physics research.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'kobe-u',
    name: 'Kobe University',
    city: 'Kobe',
    country: 'Hyogo',
    type: 'University',
    department: 'Graduate School of Science, Department of Physics',
    researchGroup: 'Theoretical Physics, Astrophysics',
    url: 'https://www.kobe-u.ac.jp/',
    fields: 'Theoretical Physics|Astrophysics|Condensed Matter|Particle Physics|Quantum Physics|Biophysics',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Nov prior year', october_intake: 'May same year', rolling: true },
    internationalTuitionJpy: 535800,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 143000,
      mextEligible: true,
      jspsEligible: true,
      imperialUniversity: false,
      jspSKakenhi: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'MEXT Scholarship or JSPS Fellowship',
    monthlyJpy: 143000,
    languageInstruction: 'English (many groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Masataka Fukugita (Theoretical Astrophysics), Prof. Toshikazu Ebisuzaki (Computational Astrophysics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL, motivation letter',
    notesForNepali: 'Kobe University has strong Theoretical Physics and connections to RIKEN. MEXT fully funded. Kobe is a beautiful port city.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'hiroshima-u',
    name: 'Hiroshima University',
    city: 'Hiroshima',
    country: 'Hiroshima',
    type: 'University',
    department: 'Graduate School of Advanced Science and Engineering',
    researchGroup: 'Radiation Physics, Nuclear Physics',
    url: 'https://www.hiroshima-u.ac.jp/',
    fields: 'Radiation Physics|Nuclear Physics|Particle Physics|Condensed Matter|Materials Science|Biophysics',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Nov prior year', october_intake: 'May same year', rolling: true },
    internationalTuitionJpy: 535800,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 143000,
      mextEligible: true,
      jspsEligible: true,
      imperialUniversity: false,
      jspSKakenhi: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'MEXT Scholarship or JSPS Fellowship',
    monthlyJpy: 143000,
    languageInstruction: 'English (many groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Kiyoshi Kato (Nuclear Physics), Prof. Toshio Yanagida (Theoretical Physics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL, motivation letter',
    notesForNepali: 'Hiroshima University is strong in Radiation Physics and Nuclear Physics. MEXT fully funded. Historical city with lower cost of living.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'okayama-u',
    name: 'Okayama University',
    city: 'Okayama',
    country: 'Okayama',
    type: 'University',
    department: 'Graduate School of Natural Science and Technology',
    researchGroup: 'Quantum Physics, Materials Science',
    url: 'https://www.okayama-u.ac.jp/',
    fields: 'Quantum Physics|Materials Science|Condensed Matter|Applied Physics|Photonics|Nuclear Physics',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Nov prior year', october_intake: 'May same year', rolling: true },
    internationalTuitionJpy: 535800,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 143000,
      mextEligible: true,
      jspsEligible: true,
      imperialUniversity: false,
      jspSKakenhi: false,
    },
    ieltsMinimum: 6.0,
    contractType: 'MEXT Scholarship',
    monthlyJpy: 143000,
    languageInstruction: 'English (some groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Toshiaki Tanii (Quantum Devices), Prof. Akira Tonomura (Electron Holography, formerly)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL, motivation letter',
    notesForNepali: 'Okayama University has good programs in Quantum Physics and Materials Science. MEXT fully funded. Affordable city with warm climate.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'yokohama-nu',
    name: 'Yokohama National University',
    city: 'Yokohama',
    country: 'Kanagawa',
    type: 'University',
    department: 'Graduate School of Engineering Science',
    researchGroup: 'Applied Physics, Photonics',
    url: 'https://www.ynu.ac.jp/',
    fields: 'Applied Physics|Photonics|Materials Science|Quantum Physics|Condensed Matter|Nanotechnology',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Nov prior year', october_intake: 'May same year', rolling: true },
    internationalTuitionJpy: 535800,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 143000,
      mextEligible: true,
      jspsEligible: true,
      imperialUniversity: false,
      jspSKakenhi: false,
    },
    ieltsMinimum: 6.0,
    contractType: 'MEXT Scholarship',
    monthlyJpy: 143000,
    languageInstruction: 'English (some groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Takayoshi Kobayashi (Photonics), Prof. Masahito Ueda (Quantum Physics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL, motivation letter',
    notesForNepali: 'YNU is near Tokyo with strong Applied Physics and Photonics. MEXT fully funded. Yokohama is a vibrant international city.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'waseda-u',
    name: 'Waseda University',
    city: 'Tokyo',
    country: 'Tokyo',
    type: 'University',
    department: 'School of Advanced Science and Engineering',
    researchGroup: 'Applied Physics, Photonics, Quantum Information',
    url: 'https://www.waseda.jp/',
    fields: 'Applied Physics|Photonics|Quantum Information|Condensed Matter|Materials Science|Nanotechnology',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Nov prior year', october_intake: 'May same year', rolling: true },
    internationalTuitionJpy: 800000,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 120000,
      mextEligible: true,
      jspsEligible: false,
      imperialUniversity: false,
      jspSKakenhi: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'University Scholarship or MEXT',
    monthlyJpy: 120000,
    languageInstruction: 'English (many groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Kazuo Kitahara (Statistical Physics), Prof. Kenichi Ohki (Quantum Information)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL, motivation letter',
    notesForNepali: 'Waseda is a prestigious private university with strong Applied Physics. MEXT eligible. Higher tuition but scholarships available.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'keio-u',
    name: 'Keio University',
    city: 'Yokohama',
    country: 'Kanagawa',
    type: 'University',
    department: 'Faculty of Science and Technology, Department of Physics',
    researchGroup: 'Physics, Photonics',
    url: 'https://www.keio.ac.jp/',
    fields: 'Physics|Photonics|Condensed Matter|Quantum Information|Materials Science|Applied Physics',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Nov prior year', october_intake: 'May same year', rolling: true },
    internationalTuitionJpy: 900000,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 120000,
      mextEligible: true,
      jspsEligible: false,
      imperialUniversity: false,
      jspSKakenhi: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'University Scholarship or MEXT',
    monthlyJpy: 120000,
    languageInstruction: 'English (some groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Yoshihisa Yamamoto (Quantum Optics), Prof. Hideo Mabuchi (Quantum Information)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL, motivation letter',
    notesForNepali: 'Keio is a top private university with strong Photonics research. MEXT eligible. Higher tuition but scholarships available.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'tokyo-u-science',
    name: 'Tokyo University of Science',
    city: 'Tokyo',
    country: 'Tokyo',
    type: 'University',
    department: 'Faculty of Science, Department of Physics',
    researchGroup: 'Applied Physics, Materials Science',
    url: 'https://www.tus.ac.jp/',
    fields: 'Applied Physics|Materials Science|Condensed Matter|Quantum Physics|Photonics|Nanotechnology',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Nov prior year', october_intake: 'May same year', rolling: true },
    internationalTuitionJpy: 800000,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 100000,
      mextEligible: true,
      jspsEligible: false,
      imperialUniversity: false,
      jspSKakenhi: false,
    },
    ieltsMinimum: 6.0,
    contractType: 'University Scholarship or MEXT',
    monthlyJpy: 100000,
    languageInstruction: 'English (some groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Makoto Watanabe (Applied Physics), Prof. Koichiro Tanaka (Terahertz Physics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL, motivation letter',
    notesForNepali: 'Tokyo University of Science has strong Applied Physics programs. MEXT eligible. Good for students interested in practical applications.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'osaka-metropolitan-u',
    name: 'Osaka Metropolitan University',
    city: 'Osaka',
    country: 'Osaka',
    type: 'University',
    department: 'Graduate School of Science',
    researchGroup: 'Astrophysics, Condensed Matter',
    url: 'https://www.omu.ac.jp/',
    fields: 'Astrophysics|Condensed Matter|Particle Physics|Materials Science|Quantum Physics|Nuclear Physics',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Nov prior year', october_intake: 'May same year', rolling: true },
    internationalTuitionJpy: 535800,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 100000,
      mextEligible: true,
      jspsEligible: false,
      imperialUniversity: false,
      jspSKakenhi: false,
    },
    ieltsMinimum: 6.0,
    contractType: 'University Scholarship or MEXT',
    monthlyJpy: 100000,
    languageInstruction: 'English (some groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Naoto Nagaosa (Theoretical Physics, visiting), Prof. Yasushi Suto (Astrophysics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL, motivation letter',
    notesForNepali: 'Osaka Metropolitan University (formerly Osaka City University) has good Astrophysics. MEXT eligible. Lower cost of living in Osaka.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'chiba-u',
    name: 'Chiba University',
    city: 'Chiba',
    country: 'Chiba',
    type: 'University',
    department: 'Graduate School of Science and Engineering',
    researchGroup: 'Photonics, Quantum Electronics',
    url: 'https://www.chiba-u.ac.jp/',
    fields: 'Photonics|Quantum Electronics|Condensed Matter|Materials Science|Applied Physics|Nanotechnology',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Nov prior year', october_intake: 'May same year', rolling: true },
    internationalTuitionJpy: 535800,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 100000,
      mextEligible: true,
      jspsEligible: false,
      imperialUniversity: false,
      jspSKakenhi: false,
    },
    ieltsMinimum: 6.0,
    contractType: 'University Scholarship or MEXT',
    monthlyJpy: 100000,
    languageInstruction: 'English (some groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Masahiro Kitagawa (Quantum Information), Prof. Kaoru Minoshima (Photonics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL, motivation letter',
    notesForNepali: 'Chiba University has strong Photonics and Quantum Electronics. MEXT eligible. Near Tokyo with lower living costs.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'shinshu-u',
    name: 'Shinshu University',
    city: 'Nagano',
    country: 'Nagano',
    type: 'University',
    department: 'Faculty of Engineering',
    researchGroup: 'Carbon Nanomaterials, Fibre Physics',
    url: 'https://www.shinshu-u.ac.jp/',
    fields: 'Carbon Nanomaterials|Fibre Physics|Materials Science|Condensed Matter|Applied Physics|Nanotechnology',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Nov prior year', october_intake: 'May same year', rolling: true },
    internationalTuitionJpy: 535800,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 100000,
      mextEligible: true,
      jspsEligible: false,
      imperialUniversity: false,
      jspSKakenhi: false,
    },
    ieltsMinimum: 6.0,
    contractType: 'University Scholarship or MEXT',
    monthlyJpy: 100000,
    languageInstruction: 'English (some groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Morinobu Endo (Carbon Nanotubes pioneer), Prof. Kenji Hata (Nanotechnology)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL, motivation letter',
    notesForNepali: 'Shinshu University is world-famous for Carbon Nanomaterials research (Prof. Endo is a carbon nanotube pioneer). MEXT eligible. Nagano is beautiful and affordable.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'toho-u',
    name: 'Toho University',
    city: 'Funabashi',
    country: 'Chiba',
    type: 'University',
    department: 'Faculty of Science, Department of Physics',
    researchGroup: 'Astronomy, Astrophysics',
    url: 'https://www.toho-u.ac.jp/',
    fields: 'Astronomy|Astrophysics|Condensed Matter|Theoretical Physics|Quantum Physics|Materials Science',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Nov prior year', october_intake: 'May same year', rolling: true },
    internationalTuitionJpy: 700000,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 100000,
      mextEligible: true,
      jspsEligible: false,
      imperialUniversity: false,
      jspSKakenhi: false,
    },
    ieltsMinimum: 6.0,
    contractType: 'University Scholarship or MEXT',
    monthlyJpy: 100000,
    languageInstruction: 'English (some groups)',
    englishLabLife: true,
    notableProfessors: 'Prof. Maki Kawai (Surface Science, formerly), Prof. Yasushi Fukuda (Astrophysics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL, motivation letter',
    notesForNepali: 'Toho University has good Astronomy and Astrophysics programs. MEXT eligible. Small but focused research environment.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },

  // ========================
  // NATIONAL INSTITUTES & RESEARCH INSTITUTES
  // ========================
  {
    id: 'riken',
    name: 'RIKEN',
    city: 'Wako',
    country: 'Saitama',
    type: 'National Institute',
    department: 'Multiple research centers',
    researchGroup: 'Quantum Computing, Particle Physics, Condensed Matter, Nuclear Physics',
    url: 'https://www.riken.jp/',
    fields: 'Quantum Computing|Particle Physics|Condensed Matter|Nuclear Physics|Quantum Information|Materials Science',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Oct prior year', october_intake: 'Apr same year', rolling: true },
    internationalTuitionJpy: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 209000,
      mextEligible: false,
      jspsEligible: true,
      imperialUniversity: false,
      jspSKakenhi: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'JSPS Fellowship or RIKEN Special Postdoctoral Researcher',
    monthlyJpy: 209000,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Dr. Yasunobu Nakamura (Quantum Computing), Dr. Hideki Yukawa legacy (Nuclear Physics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'RIKEN is Japan\'s premier research institute. JSPS Fellowship provides ¥209,000/month. No tuition fees! World-class facilities and international environment.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'kek',
    name: 'KEK (High Energy Accelerator Research Organization)',
    city: 'Tsukuba',
    country: 'Ibaraki',
    type: 'National Institute',
    department: 'Institute of Particle and Nuclear Studies',
    researchGroup: 'Particle Physics, Accelerator Physics',
    url: 'https://www.kek.jp/',
    fields: 'Particle Physics|Accelerator Physics|Nuclear Physics|Particle Phenomenology|Neutrino Physics|Cosmology',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Oct prior year', october_intake: 'Apr same year', rolling: true },
    internationalTuitionJpy: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 209000,
      mextEligible: false,
      jspsEligible: true,
      imperialUniversity: false,
      jspSKakenhi: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'JSPS Fellowship or KEK Researcher',
    monthlyJpy: 209000,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof. Masanori Yamauchi (Director General), Prof. Kazunori Hanagaki (Particle Physics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'KEK is Japan\'s premier particle physics lab. Home to SuperKEKB, Belle II, and J-PARC. JSPS Fellowship provides ¥209,000/month. No tuition!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'jaea',
    name: 'JAEA (Japan Atomic Energy Agency)',
    city: 'Tokai',
    country: 'Ibaraki',
    type: 'National Institute',
    department: 'Nuclear Science and Engineering Center',
    researchGroup: 'Nuclear Physics, Radiation Science',
    url: 'https://www.jaea.go.jp/',
    fields: 'Nuclear Physics|Radiation Science|Nuclear Engineering|Particle Physics|Materials Science|Nuclear Safety',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Oct prior year', october_intake: 'Apr same year', rolling: true },
    internationalTuitionJpy: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 200000,
      mextEligible: false,
      jspsEligible: true,
      imperialUniversity: false,
      jspSKakenhi: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'JSPS Fellowship or JAEA Researcher',
    monthlyJpy: 200000,
    languageInstruction: 'English (some groups)',
    englishLabLife: true,
    notableProfessors: 'Dr. Koji Oda (Nuclear Physics), Dr. Toshio Shibata (Radiation Science)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'JAEA focuses on nuclear physics and radiation science. JSPS eligible. ¥200,000/month. Important for students interested in nuclear energy research.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'nifs',
    name: 'NIFS (National Institute for Fusion Science)',
    city: 'Toki',
    country: 'Gifu',
    type: 'National Institute',
    department: 'Fusion Research',
    researchGroup: 'Plasma Physics, Fusion Science',
    url: 'https://www.nifs.ac.jp/',
    fields: 'Plasma Physics|Fusion Science|Computational Physics|Magnetohydrodynamics|Astrophysical Plasmas|Nuclear Fusion',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Oct prior year', october_intake: 'Apr same year', rolling: true },
    internationalTuitionJpy: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 200000,
      mextEligible: false,
      jspsEligible: true,
      imperialUniversity: false,
      jspSKakenhi: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'JSPS Fellowship or NIFS Researcher',
    monthlyJpy: 200000,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof. Akio Sagara (Fusion Engineering), Prof. Yasuhiro Kishimoto (Plasma Simulation)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'NIFS is Japan\'s premier fusion research center. Home to the Large Helical Device (LHD). JSPS eligible. ¥200,000/month. Great for plasma physics students.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'ipmu',
    name: 'IPMU (Kavli IPMU, UTokyo)',
    city: 'Kashiwa',
    country: 'Chiba',
    type: 'Research Institute',
    department: 'Kavli Institute for the Physics and Mathematics of the Universe',
    researchGroup: 'Cosmology, Astroparticle Physics, String Theory',
    url: 'https://www.ipmu.jp/',
    fields: 'Cosmology|Astroparticle Physics|String Theory|Particle Physics|Theoretical Physics|Mathematical Physics',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Oct prior year', october_intake: 'Apr same year', rolling: true },
    internationalTuitionJpy: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 209000,
      mextEligible: false,
      jspsEligible: true,
      imperialUniversity: false,
      jspSKakenhi: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'JSPS Fellowship or IPMU Postdoctoral Researcher',
    monthlyJpy: 209000,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof. Hitoshi Murayama (Director, Particle Physics), Prof. Toshikazu Ebisuzaki (Astrophysics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'Kavli IPMU is a world-leading institute for Cosmology and String Theory. JSPS Fellowship ¥209,000/month. No tuition. Extremely international environment!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'naoj',
    name: 'NAOJ (National Astronomical Observatory of Japan)',
    city: 'Mitaka',
    country: 'Tokyo',
    type: 'National Institute',
    department: 'Astronomical Research',
    researchGroup: 'Astronomy, Astrophysics, Radio Astronomy',
    url: 'https://www.nao.ac.jp/',
    fields: 'Astronomy|Astrophysics|Radio Astronomy|Optical Astronomy|Stellar Physics|Planetary Science',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Oct prior year', october_intake: 'Apr same year', rolling: true },
    internationalTuitionJpy: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 200000,
      mextEligible: false,
      jspsEligible: true,
      imperialUniversity: false,
      jspSKakenhi: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'JSPS Fellowship or NAOJ Researcher',
    monthlyJpy: 200000,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Prof. Nobumitsu Ito (Stellar Evolution), Prof. Mareki Honma (VLBI Astronomy)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'NAOJ operates the Subaru Telescope and ALMA. JSPS eligible. ¥200,000/month. Excellent for Astrophysics students from Nepal!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'jamstec',
    name: 'JAMSTEC (Japan Agency for Marine-Earth Science and Technology)',
    city: 'Yokosuka',
    country: 'Kanagawa',
    type: 'National Institute',
    department: 'Research Institute for Global Change',
    researchGroup: 'Geophysics, Earth Science',
    url: 'https://www.jamstec.go.jp/',
    fields: 'Geophysics|Earth Science|Ocean Physics|Climate Science|Seismology|Computational Geoscience',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Oct prior year', october_intake: 'Apr same year', rolling: true },
    internationalTuitionJpy: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 200000,
      mextEligible: false,
      jspsEligible: true,
      imperialUniversity: false,
      jspSKakenhi: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'JSPS Fellowship or JAMSTEC Researcher',
    monthlyJpy: 200000,
    languageInstruction: 'English (some groups)',
    englishLabLife: true,
    notableProfessors: 'Dr. Yuko Tanaka (Geophysics), Dr. Shuhei Nishida (Ocean Physics)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'JAMSTEC is excellent for Geophysics and Earth Science. JSPS eligible. ¥200,000/month. Operates deep-sea research vessels and Earth Simulator supercomputer.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'qst',
    name: 'QST (National Institutes for Quantum and Radiological Science and Technology)',
    city: 'Chiba',
    country: 'Chiba',
    type: 'National Institute',
    department: 'Quantum Beam Science Research',
    researchGroup: 'Quantum Beam Science, Radiation Research',
    url: 'https://www.qst.go.jp/',
    fields: 'Quantum Beam Science|Radiation Research|Medical Physics|Materials Science|Particle Therapy|Nuclear Science',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Oct prior year', october_intake: 'Apr same year', rolling: true },
    internationalTuitionJpy: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 200000,
      mextEligible: false,
      jspsEligible: true,
      imperialUniversity: false,
      jspSKakenhi: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'JSPS Fellowship or QST Researcher',
    monthlyJpy: 200000,
    languageInstruction: 'English (some groups)',
    englishLabLife: true,
    notableProfessors: 'Dr. Toshio Hirao (Quantum Beams), Dr. Masahiro Okada (Radiation Research)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'QST focuses on quantum beam science and radiation research. JSPS eligible. ¥200,000/month. Important for medical physics and radiation science students.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'riken-cqc',
    name: 'RIKEN Center for Quantum Computing',
    city: 'Wako',
    country: 'Saitama',
    type: 'National Institute',
    department: 'Quantum Computing Center',
    researchGroup: 'Quantum Computing, Quantum Information',
    url: 'https://cqc.riken.jp/',
    fields: 'Quantum Computing|Quantum Information|Quantum Error Correction|Superconducting Qubits|Quantum Algorithms|Quantum Simulation',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Oct prior year', october_intake: 'Apr same year', rolling: true },
    internationalTuitionJpy: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 209000,
      mextEligible: false,
      jspsEligible: true,
      imperialUniversity: false,
      jspSKakenhi: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'JSPS Fellowship or RIKEN Researcher',
    monthlyJpy: 209000,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Dr. Yasunobu Nakamura (Superconducting Qubits), Dr. Franco Nori (Quantum Information)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'RIKEN CQC is Japan\'s flagship quantum computing center. JSPS Fellowship ¥209,000/month. No tuition. World-leading quantum computing research!',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
  {
    id: 'aist',
    name: 'AIST (National Institute of Advanced Industrial Science and Technology)',
    city: 'Tsukuba',
    country: 'Ibaraki',
    type: 'National Institute',
    department: 'Nanomaterials Research Institute',
    researchGroup: 'Materials Science, Nanotechnology',
    url: 'https://www.aist.go.jp/',
    fields: 'Materials Science|Nanotechnology|Condensed Matter|Quantum Materials|Photonics|Energy Materials',
    phdType: 'PhD (3-5 years)',
    deadline: 'Rolling admissions',
    admission: 'Rolling',
    deadlines: { april_intake: 'Oct prior year', october_intake: 'Apr same year', rolling: true },
    internationalTuitionJpy: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendJpy: 200000,
      mextEligible: false,
      jspsEligible: true,
      imperialUniversity: false,
      jspSKakenhi: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'JSPS Fellowship or AIST Researcher',
    monthlyJpy: 200000,
    languageInstruction: 'English (some groups)',
    englishLabLife: true,
    notableProfessors: 'Dr. Kohei Uosaki (Electrochemistry), Dr. Tomonobu Nakayama (Nanotechnology)',
    requiredDocuments: 'CV, MSc transcripts, research proposal, 2 reference letters, IELTS/TOEFL',
    notesForNepali: 'AIST is Japan\'s largest public research institute. JSPS eligible. ¥200,000/month. Strong in Materials Science and Nanotechnology.',
    watchlisted: false,
    lastUpdated: '2025-01',
    go8: false,
  },
]

// ─────────────────────────────────────────────
// SCHOLARSHIPS FOR JAPAN
// ─────────────────────────────────────────────
export const scholarships: ScholarshipInfo[] = [
  {
    id: 'mext',
    title: 'MEXT Scholarship (Monbukagakusho)',
    category: 'Government',
    content: 'Full tuition waiver + ¥143,000/month + round-trip airfare from Nepal + arrival allowance. The MOST IMPORTANT scholarship for Nepali students. Covers entire PhD duration (3-5 years). Apply through Japanese Embassy in Nepal (Embassy Recommendation) or through university (University Recommendation). February-April application period for Embassy route.',
  },
  {
    id: 'jsps',
    title: 'JSPS Fellowship',
    category: 'Government',
    content: '¥209,000/month for postdoctoral and research positions. Japan Society for the Promotion of Science offers fellowships for international researchers. Excellent for students at RIKEN, KEK, NIFS, and other national institutes. Typically 1-3 years, renewable.',
  },
  {
    id: 'jasso',
    title: 'JASSO Scholarship',
    category: 'Government',
    content: '¥48,000-80,000/month for short-term exchange and study. Japan Student Services Organization provides support for privately financed international students. Good supplementary income while pursuing PhD.',
  },
  {
    id: 'adb-jsp',
    title: 'ADB-JSP Scholarship',
    category: 'International',
    content: 'Full tuition + living allowance + travel from Nepal. Asian Development Bank Japan Scholarship Program. Available at designated Japanese universities. Covers entire study period including PhD.',
  },
  {
    id: 'wb-jj',
    title: 'World Bank Joint Japan Scholarship',
    category: 'International',
    content: 'Full tuition + living allowance + travel. World Bank Joint Japan/Graduate Scholarship Program. For students from developing countries including Nepal. Available at participating Japanese universities.',
  },
  {
    id: 'uni-specific',
    title: 'University-specific Scholarships (UTokyo, KyotoU)',
    category: 'University',
    content: 'Varies by university, ¥80,000-150,000/month. Top Japanese universities offer their own scholarships for international PhD students. UTokyo offers multiple scholarships through its Fellowships Office. KyotoU also has generous programs.',
  },
  {
    id: 'mext-honors',
    title: 'Honors Scholarship (MEXT)',
    category: 'Government',
    content: '¥48,000/month for privately financed international students. MEXT provides this scholarship as supplementary support for students who do not receive the full MEXT scholarship. Apply through your university after enrollment.',
  },
  {
    id: 'rotary-yoneyama',
    title: 'Rotary Yoneyama Scholarship',
    category: 'Private',
    content: '¥100,000-140,000/month. Rotary Club of Japan\'s Yoneyama Scholarship for international students. Apply through Rotary districts in Japan. Available for doctoral students. Requires recommendation from a Rotary club.',
  },
  {
    id: 'otsuka-toshimi',
    title: 'Otsuka Toshimi Scholarship',
    category: 'Private',
    content: '¥100,000-200,000/month. Otsuka Toshimi Foundation Scholarship for international students in Japan. Competitive but generous. Available for PhD students in science fields.',
  },
  {
    id: 'heiwa-nakajima',
    title: 'Heiwa Nakajima Foundation',
    category: 'Private',
    content: '¥120,000/month. Heiwa Nakajima Foundation Scholarship for international students. Available for doctoral students. Renewable for the duration of studies.',
  },
  {
    id: 'mext-teacher',
    title: 'MEXT Teacher Training Scholarship',
    category: 'Government',
    content: '¥143,000/month for teacher training and educational research. MEXT offers this for educators and researchers in educational fields. Can be relevant for physics education research.',
  },
]

// ─────────────────────────────────────────────
// SEARCH SCHOLARSHIPS
// ─────────────────────────────────────────────
export function searchScholarships(query: string): ScholarshipInfo[] {
  const q = query.toLowerCase()
  return scholarships.filter(
    (s) =>
      s.title.toLowerCase().includes(q) ||
      s.category.toLowerCase().includes(q) ||
      s.content.toLowerCase().includes(q)
  )
}
